name: PromCI
description: An action used by the Prometheus project to share github actions.
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        repository: 'prometheus/promci'
        path: '.github/promci'
        ref: v0.0.2
