name: PromCI
description: An action used by the Prometheus project to share github actions.
runs:
  using: composite
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: 'prometheus/promci'
        path: '.github/promci'
        ref: v0.4.4
